# Generated by Django 5.0.4 on 2024-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Kunde')),
                ('location', models.CharField(max_length=50, verbose_name='Ort')),
                ('contract_date', models.DateField(verbose_name='Datum')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Makler Suchauftrag Vorlage',
                'verbose_name_plural': 'Makler Suchauftrag Vorlage',
            },
        ),
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord', models.CharField(max_length=100, verbose_name='Vermieter')),
                ('renter', models.CharField(max_length=100, verbose_name='Mieter')),
                ('resident', models.CharField(max_length=30, verbose_name='Wohnhaft')),
                ('passport', models.CharField(max_length=20, verbose_name='Passport')),
                ('date_of_expiry', models.CharField(max_length=20, verbose_name='Gültig bis')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('rooms', models.CharField(max_length=10, verbose_name='Zimmer')),
                ('balcony', models.CharField(max_length=10, verbose_name='Balkon')),
                ('area', models.CharField(max_length=10, verbose_name='Wohnungsbereich')),
                ('start_date', models.CharField(max_length=20, verbose_name='Beginnt')),
                ('stop_date', models.CharField(max_length=20, verbose_name='Endet')),
                ('iban', models.CharField(max_length=50, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=50, verbose_name='BIC')),
                ('credit_institution', models.CharField(max_length=50, verbose_name='Kreditinstitut')),
                ('purpose', models.CharField(max_length=20, verbose_name='Zweck')),
                ('monthly_rent', models.CharField(max_length=10, verbose_name='Monatliche Grundmiete')),
                ('extra_costs', models.CharField(max_length=10, verbose_name='Nebenkosten')),
                ('deposit', models.CharField(max_length=10, verbose_name='Kaution')),
                ('persons', models.CharField(max_length=500, verbose_name='Personen')),
                ('location', models.CharField(max_length=50, verbose_name='Ort')),
                ('contract_date', models.DateField(verbose_name='Datum')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Mietvertrag Stallschreiberstr',
                'verbose_name_plural': 'Mietvertrag Stallschreiberstr',
            },
        ),
        migrations.CreateModel(
            name='SaleContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Kunde')),
                ('object', models.CharField(max_length=100, verbose_name='Objekt')),
                ('land_register', models.CharField(max_length=100, verbose_name='Grundbuch')),
                ('length_of_time', models.CharField(max_length=10, verbose_name='Dauer')),
                ('address', models.CharField(max_length=50, verbose_name='Adresse')),
                ('position', models.CharField(max_length=100, verbose_name='Lage')),
                ('location', models.CharField(max_length=50, verbose_name='Ort')),
                ('contract_date', models.DateField(verbose_name='Datum')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Maklervertrag Verkauf',
                'verbose_name_plural': 'Maklervertrag Verkauf',
            },
        ),
        migrations.CreateModel(
            name='SearchContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Eigentümer')),
                ('address', models.CharField(max_length=50, verbose_name='Adresse')),
                ('area', models.CharField(max_length=10, verbose_name='Hausbereich')),
                ('deposit', models.CharField(max_length=10, verbose_name='Einzahlung')),
                ('purchase_contract', models.CharField(max_length=50, verbose_name='Kaufvertrag')),
                ('land_register', models.CharField(max_length=50, verbose_name='Grundbuchauszug')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Mietersuche Vertrag',
                'verbose_name_plural': 'Mietersuche Vertrag',
            },
        ),
    ]
