# Generated by Django 5.0.4 on 2024-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=90, verbose_name='Kunde')),
                ('location', models.CharField(max_length=35, verbose_name='Ort')),
                ('contract_date', models.DateField(verbose_name='Datum')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Makler Suchauftrag Vorlage',
                'verbose_name_plural': 'Makler Suchauftrag Vorlage',
            },
        ),
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord', models.CharField(max_length=90, verbose_name='Vermieter')),
                ('renter', models.CharField(max_length=90, verbose_name='Mieter')),
                ('resident', models.CharField(max_length=50, verbose_name='Wohnhaft')),
                ('passport', models.CharField(max_length=30, verbose_name='Passport')),
                ('date_of_expiry', models.DateField(verbose_name='Gültig bis')),
                ('address', models.CharField(max_length=50, verbose_name='Adresse')),
                ('floor', models.CharField(max_length=30, verbose_name='Etage')),
                ('rooms', models.SmallIntegerField(verbose_name='Zimmer')),
                ('kitchen', models.SmallIntegerField(verbose_name='Küche')),
                ('corridor', models.IntegerField(verbose_name='Korridor')),
                ('balcony', models.SmallIntegerField(verbose_name='Balkon')),
                ('bathroom', models.SmallIntegerField(verbose_name='Badezimmer')),
                ('utility_room', models.SmallIntegerField(verbose_name='Keller')),
                ('area', models.FloatField(verbose_name='Wohnungsbereich')),
                ('furniture', models.CharField(choices=[('voll möbliert', 'voll möbliert'), ('teilmöbliert', 'teilmöbliert'), ('ohne möbel', 'ohne möbel')], max_length=50)),
                ('start_date', models.DateField(verbose_name='Beginnt')),
                ('stop_date', models.DateField(verbose_name='Endet')),
                ('rent_stop_date', models.DateField(verbose_name='Kündigungsdatum der Miete')),
                ('recipient', models.CharField(max_length=90, verbose_name='Empfänger')),
                ('iban', models.CharField(max_length=50, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=50, verbose_name='BIC')),
                ('credit_institution', models.CharField(max_length=70, verbose_name='Kreditinstitut')),
                ('purpose', models.CharField(max_length=70, verbose_name='Zweck')),
                ('monthly_rent', models.IntegerField(verbose_name='Monatliche Grundmiete')),
                ('extra_costs', models.IntegerField(verbose_name='Nebenkosten')),
                ('deposit', models.IntegerField(verbose_name='Kaution')),
                ('persons', models.CharField(max_length=200, verbose_name='Personen')),
                ('location', models.CharField(max_length=35, verbose_name='Ort')),
                ('contract_date', models.DateField(verbose_name='Datum')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Mietvertrag',
                'verbose_name_plural': 'Mietvertrag',
            },
        ),
        migrations.CreateModel(
            name='SaleContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=90, verbose_name='Kunde')),
                ('address', models.CharField(max_length=60, verbose_name='Adresse')),
                ('object', models.CharField(max_length=70, verbose_name='Objekt')),
                ('land_register', models.CharField(blank=True, max_length=50, verbose_name='Grundbuch')),
                ('length_of_time', models.IntegerField(verbose_name='Dauer')),
                ('location', models.CharField(max_length=35, verbose_name='Ort')),
                ('contract_date', models.DateField(verbose_name='Datum')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Maklervertrag Verkauf',
                'verbose_name_plural': 'Maklervertrag Verkauf',
            },
        ),
        migrations.CreateModel(
            name='SearchContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=90, verbose_name='Eigentümer')),
                ('address_customer', models.CharField(max_length=60, verbose_name='Adresse des Eigentümers')),
                ('address', models.CharField(max_length=60, verbose_name='Adresse')),
                ('floor', models.CharField(max_length=30, verbose_name='Etage')),
                ('rooms', models.IntegerField(verbose_name='Zimmer')),
                ('corridor', models.IntegerField(verbose_name='Korridor')),
                ('balcony', models.IntegerField(verbose_name='Balkon')),
                ('bathroom', models.SmallIntegerField(verbose_name='Badezimmer')),
                ('furniture', models.CharField(choices=[('voll möbliert$с мебелью', 'voll möbliert'), ('teilmöbliert$частично меблированная', 'teilmöbliert'), ('ohne möbel$без мебели', 'ohne möbel')], max_length=50)),
                ('area', models.FloatField(verbose_name='Gesamtfläche')),
                ('deposit', models.IntegerField(verbose_name='Kaltmiete')),
                ('purchase_contract', models.CharField(blank=True, max_length=50, verbose_name='Kaufvertrag')),
                ('land_register', models.CharField(blank=True, max_length=50, verbose_name='Grundbuchauszug')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Mietersuche Vertrag',
                'verbose_name_plural': 'Mietersuche Vertrag',
            },
        ),
    ]
