# Generated by Django 5.0.4 on 2025-11-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_generator', '0002_salecontractall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleContractAll',
        ),
    ]
