# Generated by Django 5.0.4 on 2026-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_generator', '0003_delete_salecontractall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleContractAlleinauftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=90, verbose_name='Kunde')),
                ('address', models.CharField(max_length=60, verbose_name='Adresse')),
                ('object', models.CharField(max_length=70, verbose_name='Objekt')),
                ('land_register', models.CharField(blank=True, max_length=50, verbose_name='Grundbuch')),
                ('length_of_time', models.IntegerField(verbose_name='Dauer')),
                ('location', models.CharField(max_length=35, verbose_name='Ort')),
                ('contract_date', models.DateField(verbose_name='Datum')),
                ('pdf_document', models.FileField(upload_to='pdf_documents')),
            ],
            options={
                'verbose_name': 'Maklervertrag Verkauf Alleinauftrag',
                'verbose_name_plural': 'Maklervertrag Verkauf Alleinauftrag',
            },
        ),
    ]
